### ISSUE TITLE
Wrong gpudb version in Dockerfile

### ISSUE THREAD

**Issue by msvana** [kineticadb/container-kml-blackbox-sdk#1]
Your Dockerfile contains this line:
`RUN pip install gpudb==7.0.0.0 zmq requests`

This does not work with version 7.0.1 of the platform.

I think it should be:
`RUN pip install gpudb==7.0.1.0 zmq requests`

**Comment by saifrahmed** [comment]
Thank you for noting this. We have corrected this and also added startup checks to prevent it in the future.
